# Generated by Django 4.2.3 on 2023-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Staff'), (1, 'Candidate'), (2, 'Recruiter')], null=True),
        ),
    ]
