# Generated by Django 4.2.3 on 2023-07-12 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('image', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/Category/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=221)),
                ('slug', models.SlugField(blank=True, null=True, unique_for_date='created_date')),
                ('description', ckeditor.fields.RichTextField()),
                ('vacancy', models.IntegerField()),
                ('salary', models.CharField(max_length=221)),
                ('nature', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Remote')])),
                ('experience', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
